"""Shared CDP timeouts and screenshot constants."""

from .screenshot_utils import (
    SCREENSHOT_BLANK_BYTES_PER_PIXEL_THRESHOLD as SCREENSHOT_BLANK_BYTES_PER_PIXEL_THRESHOLD,
)
from .screenshot_utils import (
    SCREENSHOT_BLANK_LUMINANCE_STDDEV_THRESHOLD as SCREENSHOT_BLANK_LUMINANCE_STDDEV_THRESHOLD,
)
from .screenshot_utils import (
    SCREENSHOT_BLANK_MAX_RETRIES as SCREENSHOT_BLANK_MAX_RETRIES,
)
from .screenshot_utils import (
    SCREENSHOT_BLANK_RETRY_DELAY_SECONDS as SCREENSHOT_BLANK_RETRY_DELAY_SECONDS,
)
from .screenshot_utils import (
    SCREENSHOT_PAINT_READY_TIMEOUT_MS as SCREENSHOT_PAINT_READY_TIMEOUT_MS,
)

REQUEST_TIMEOUT_SECONDS = 120
