"""Named-profile catalog and live-browser discovery.

Reads the on-disk profile directory under ``CACHE_DIR / 'profiles'`` and the
process table to report which browser-tools Chrome instances exist and which
are live. Pure inspection plus profile deletion; it does not launch browsers
or construct controllers. The on-disk layout (``CACHE_DIR``, profile paths,
``clear_session_files``) is owned by ``session_layout`` and imported here.
"""

from __future__ import annotations

import os
import shutil
from typing import Any

from . import session_layout as layout
from .live_chrome import resolve_live_chrome
from .process_utils import (
    enumerate_tabs,
    is_process_alive,
    terminate_process_and_wait,
)


def _is_named_profile(name: str) -> bool:
    """Check whether a directory name is a named profile (not a session key hash).

    Named profiles are human-readable names. Session key hashes are 16-char
    hex strings generated by build_session_key().

    Args:
        name: Directory name to check.

    Returns:
        True when the name looks like a human-chosen profile name.
    """
    # Session keys from build_session_key are 16-char hex strings
    if len(name) == 16:
        try:
            int(name, 16)
            return False
        except ValueError:
            pass
    return True


def list_profiles() -> list[str]:
    """List all named browser profiles.

    Returns:
        Sorted list of profile names.
    """
    profiles_dir = layout.profiles_dir()
    if not profiles_dir.exists():
        return []
    return sorted(
        d.name for d in profiles_dir.iterdir() if d.is_dir() and _is_named_profile(d.name)
    )


def list_profile_dirs() -> list[str]:
    """List every profile directory, named or hashed session key.

    ``list_profiles`` deliberately hides hashed session keys because they are
    not addressable by name. This function does not, because a hashed session's
    Chrome is just as real a browser instance as a named profile's and must be
    visible to liveness checks.

    Returns:
        Sorted list of directory names under ``CACHE_DIR / 'profiles'``.
    """
    profiles_dir = layout.profiles_dir()
    if not profiles_dir.exists():
        return []
    return sorted(d.name for d in profiles_dir.iterdir() if d.is_dir())


def describe_profile_runtime(profile_name: str) -> dict[str, Any]:
    """Describe the live state of a named profile's Chrome process.

    Args:
        profile_name: Profile directory name under ``CACHE_DIR / 'profiles'``.
            Accepts both human-named profiles and the hashed session keys used
            by default per-project sessions.

    Returns:
        Status dict with keys:
            - ``profile``: profile name.
            - ``named``: whether this is a human-named profile rather than a
              hashed per-project session key.
            - ``user_data_dir``: profile directory path string.
            - ``exists``: whether the profile directory exists.
            - ``pid``: PID of the Chrome holding the profile, or None.
            - ``intended_port``: ``--remote-debugging-port`` from the cmdline.
            - ``port``: live debug port reachable for CDP, or None.
            - ``endpoint``: ``http://127.0.0.1:<port>`` when alive, else None.
            - ``devtools_alive``: whether ``/json/version`` answered.
            - ``port_collision_pids``: other PIDs listening on intended_port
              when the holding process didn't bind it.
            - ``current_url``: URL of the first non-blank tab, when reachable.
            - ``tab_count``: number of pages reported by ``/json/list``.
    """
    profile_dir = layout.profile_dir(profile_name)
    info: dict[str, Any] = {
        "profile": profile_name,
        "named": _is_named_profile(profile_name),
        "user_data_dir": str(profile_dir),
        "exists": profile_dir.exists(),
        "pid": None,
        "intended_port": None,
        "port": None,
        "endpoint": None,
        "devtools_alive": False,
        "port_collision_pids": [],
        "current_url": None,
        "tab_count": 0,
    }
    if not profile_dir.exists():
        return info

    chrome = resolve_live_chrome(profile_dir)
    if chrome is None:
        return info
    info["pid"] = chrome.pid
    info["intended_port"] = chrome.intended_port

    if chrome.intended_port is not None:
        if chrome.devtools_alive:
            assert chrome.endpoint is not None  # set iff devtools_alive
            endpoint = chrome.endpoint
            info["port"] = chrome.port
            info["endpoint"] = endpoint
            info["devtools_alive"] = True
            tabs = enumerate_tabs(endpoint)
            info["tab_count"] = len(tabs)
            for tab in tabs:
                url = tab.get("url") or ""
                if url and url != layout.INITIAL_PAGE_URL:
                    info["current_url"] = url
                    break
        else:
            info["port_collision_pids"] = chrome.port_collision_pids
    return info


def find_live_profiles() -> list[dict[str, Any]]:
    """Return runtime descriptors for every live browser-tools Chrome.

    Covers hashed per-project session profiles as well as named ones — those
    hashed sessions are the default, so a listing that skipped them reported
    "one browser is live" while several were.

    Returns:
        List of ``describe_profile_runtime`` results filtered to those whose
        Chrome process is alive and whose DevTools endpoint answered.
    """
    live: list[dict[str, Any]] = []
    for name in list_profile_dirs():
        info = describe_profile_runtime(name)
        if info.get("devtools_alive"):
            live.append(info)
    return live


def delete_profile(name: str) -> bool:
    """Delete a named browser profile and its associated state files.

    Args:
        name: Profile name to delete.

    Returns:
        True when the profile existed and was deleted, False otherwise.
    """
    # Reject anything that isn't a plain profile name so a crafted value like
    # "../.." or "/etc" cannot escape the profiles directory and delete
    # arbitrary paths.
    if (
        not name
        or name in {".", ".."}
        or "/" in name
        or "\\" in name
        or "\x00" in name
        or os.sep in name
        or (os.altsep and os.altsep in name)
        or not _is_named_profile(name)
    ):
        return False
    try:
        profiles_root = layout.profiles_dir().resolve()
        profile_dir = layout.profile_dir(name).resolve()
    except (OSError, ValueError):
        return False
    if profile_dir.parent != profiles_root:
        return False
    if not profile_dir.exists() or not profile_dir.is_dir():
        return False

    # Quit the Chrome process holding this profile before removing the
    # directory; otherwise delete_profile leaves an orphaned Chrome running on
    # a now-deleted user-data-dir (the exact "can't close them" accumulation
    # this fixes). Also stop its MCP daemon if one is recorded.
    chrome = resolve_live_chrome(profile_dir)
    if chrome is not None:
        terminate_process_and_wait(chrome.pid, timeout=5)
    session_key = f"profile_{name}"
    daemon_pid_file = layout.daemon_pid_file(session_key)
    try:
        daemon_pid = int(daemon_pid_file.read_text().strip())
    except (OSError, ValueError):
        daemon_pid = None
    if daemon_pid is not None and is_process_alive(daemon_pid):
        terminate_process_and_wait(daemon_pid, timeout=5)

    # Remove the profile directory
    shutil.rmtree(profile_dir, ignore_errors=True)

    # Remove associated state files
    layout.clear_session_files(f"profile_{name}")

    return True
