// Regenerate the isolated upstream rendering code with Node >=22.13.
// Usage: node scripts/vendor_insight_formatter.mjs SOURCE_DIRECTORY
// SOURCE_DIRECTORY contains the four named .ts files and LICENSE from the revision below.
import { readFileSync, writeFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
const revision = '011ec3baaaaefa54eba1b41be00caf48ad3e8b51';
const source = process.argv[2];
if (!source) throw new Error('Pass the upstream source directory');
const read = name => readFileSync(`${source}/${name}.ts`, 'utf8');
const between = (text, start, end) => {
  const a = text.indexOf(start);
  const b = text.indexOf(end, a + start.length);
  if (a < 0 || b < 0) throw new Error(`Upstream boundary missing: ${start}`);
  return text.slice(a, b);
};
const write = (name, text) => writeFileSync(
  new URL(`../src/browser_tools/_insights/vendor/${name}.js`, import.meta.url),
  `// Generated by scripts/vendor_insight_formatter.mjs. Do not edit.\n// DevTools Frontend ${revision}; BSD-3-Clause, see LICENSE.\n` +
  stripTypeScriptTypes(text, {mode: 'strip'}));
let insight = read('PerformanceInsightFormatter')
  .replace("import * as Common from '../../../core/common/common.js';", "import * as Common from '../formatter_compat.js';")
  .replace("'../../trace/trace.js'", "'@paulirish/trace_engine'");
write('PerformanceInsightFormatter', insight);
write('UnitFormatters', read('UnitFormatters'));
const network = read('NetworkRequestFormatter');
write('NetworkRequestFormatter',
  between(network, 'const MAX_HEADERS_SIZE', 'export class NetworkRequestFormatter') +
  'export class NetworkRequestFormatter {\n' +
  between(network, '  static allowHeader', '  static async formatBody') + '}\n' +
  network.slice(network.indexOf('const allowedHeaders')));
const trace = read('PerformanceTraceFormatter');
write('PerformanceTraceFormatter', `
// Copyright 2025 The Chromium Authors. BSD-3-Clause.
import * as Trace from '@paulirish/trace_engine';
import {NetworkRequestFormatter} from './NetworkRequestFormatter.js';
import {micros} from './UnitFormatters.js';
// The offline adapter has no DevTools annotation repository.
const Annotations = {AnnotationRepository: {annotationsEnabled: () => false}};
export class PerformanceTraceFormatter {
  #parsedTrace;
  #eventsSerializer;
  constructor(focus) {
    this.#parsedTrace = focus.parsedTrace;
    this.#eventsSerializer = focus.eventsSerializer;
  }
` + between(trace, '  serializeEvent(', '  serializeBounds(') +
  between(trace, '  formatNetworkRequests(', '  static callFrameDataFormatDescription') +
  between(trace, '  #networkRequestCompressedFormat(', '  resolveFunctionCodeAtLocation(') + '}\n');
writeFileSync(new URL('../src/browser_tools/_insights/vendor/LICENSE', import.meta.url), readFileSync(`${source}/LICENSE`));
